# utils/word_generator.py

import os
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def generate_word(template_data, form_values, output_path):
    """
    Generate a Word document from template data and form values
    """
    try:
        # Create a new Word document
        doc = Document()
        
        # Add logo (if exists)
        logo_path = os.path.join('static', 'images', 'logo.png')
        if os.path.exists(logo_path):
            try:
                doc.add_picture(logo_path, width=Inches(1.5))
                doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.RIGHT
            except:
                pass
        
        # Title
        template_name = template_data.get('name', 'Document')
        title = doc.add_heading(template_name, 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Date
        current_date = datetime.now().strftime('%B %d, %Y')
        date_para = doc.add_paragraph(f"Generated on: {current_date}")
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add a line break
        doc.add_paragraph()
        
        # Add fields and values
        fields = template_data.get('fields', [])
        
        if fields:
            for field in fields:
                value = form_values.get(field, '')
                
                # Create a paragraph with field name and value
                para = doc.add_paragraph()
                run = para.add_run(f"{field}: ")
                run.bold = True
                run.font.size = Pt(11)
                
                run = para.add_run(value if value else '__________________')
                run.font.size = Pt(11)
        
        # Add witness section
        doc.add_paragraph()
        doc.add_heading('Witnesses', level=2)
        doc.add_paragraph('1. Name and address: _________________________')
        doc.add_paragraph('2. Name and address: _________________________')
        
        # Add signature block
        doc.add_paragraph()
        doc.add_paragraph('_________________________')
        doc.add_paragraph('Signature')
        
        doc.add_paragraph()
        doc.add_paragraph('_________________________')
        doc.add_paragraph('Date')
        
        # Add footer
        doc.add_paragraph()
        footer = doc.add_paragraph(
            'Generated by DocGen - Document Generation Platform',
            style='Normal'
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Save the document
        doc.save(output_path)
        return True
        
    except Exception as e:
        print(f"Error generating Word document: {e}")
        import traceback
        traceback.print_exc()
        return False